routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/requisiciones', function () {
    return view('/home');
});

Route::get('/requisiciones', 'RequisitionController@index');

// inyección de dependencias en Compañias
Route::bind('company', function($company){
	return App\Company::find($company);
});

// inyección de dependencias en Empresas
Route::bind('bussine', function($bussine){
	return App\Bussine::find($bussine);
});

// inyección de dependencias en areas
Route::bind('area', function($area){
	return App\Area::find($area);
});

// inyección de dependencias en proveedores
Route::bind('provider', function($provider){
	return App\Provider::find($provider);
});

Route::get('get_unread', function() {
	return Auth::user()->unreadNotifications;
});

Route::get('/notifications', 'HomeController@notifications');

Auth::routes();
Route::group(['middleware' => 'auth'], function (){

	Route::get('/home', 'HomeController@index');
	Route::resource('/company', 'CompanyController');
	Route::resource('product', 'ProductController');
	Route::get('product/subcategory/{id}', 'ProductController@getCategory');
	Route::resource('/bussine', 'BussineController');
	Route::resource('/area', 'AreaController');
	Route::resource('/provider', 'ProviderController');
	//add routes for users crud
	Route::resource('users', 'UserController');
	Route::get('/profile', 'UserController@getProfile');
	Route::post('/profile', 'UserController@postProfile'); 
	//add routes for categories crud
	Route::resource('categories', 'CategoryController');
	//add routes for subcategories crud
	Route::resource('subcategories', 'SubCategoryController');
	//add routes for requisitions crud
	Route::resource('requisitions', 'RequisitionController');
	Route::get('/api/requisitions/{id}/providers', 'RequisitionController@getProviders');
	Route::get('bussines/{id}', 'RequisitionController@getBussine');
	Route::get('requisitions/subcategory/{id}', 'RequisitionController@getCategory');
	//add routes for status change
	Route::get('requisitions/{id}/validate', 'RequisitionController@validacion');
	Route::get('requisitions/{id}/preauthorize', 'RequisitionController@preauthorize');
	Route::get('requisitions/{id}/authorizar', 'RequisitionController@authorization');
	Route::get('requisitions/{id}/process', 'RequisitionController@process');
	Route::get('requisitions/{id}/payment', 'RequisitionController@payment');
	Route::get('requisitions/{id}/rejected', 'RequisitionController@rejected');
	Route::get('requisitions/{id}/finalizadas', 'RequisitionController@finalizadas');
	Route::post('requisitions/uploadticket', [
		'uses' => 'RequisitionController@uploadticket',
		'as' 	=> 'requisitions.uploadticket'
		]);
	Route::post('requisitions/uploadvoucher', [
		'uses' => 'RequisitionController@uploadvoucher',
		'as' 	=> 'requisitions.uploadvoucher'
		]);
	//routes for comments
	Route::get('/api/requisitions/{requisition}/comments', 'CommentController@index');
	Route::post('/api/requisitions/{requisition}/comment', 'CommentController@store');
	//add routes for select bssines
	Route::get('select/bussine/{id}', 'RequisitionController@selectBussine');
	//add routes for export excel report
	Route::get('/reports-general', 'ExcelController@index');
	Route::post('/search-reports', [
		'uses' => 'ExcelController@search',
		'as' => 'searchreport.store'
		]);
	//reports requisition print
	Route::get('/export-requisition/{id}/print', 'ExcelController@exportRequisition');
	//activities
	Route::get('/activities', 'ActivityController@viewActivity');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [

        'name', 'email', 'password','lastname','address','phone','role','role_id','bussine_id','area_id'
    ];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function bussine()
    {
        return $this->belongsTo(Bussine::class);
    }

    public function area()
    {
        return $this->belongsTo(Area::class);
    }

    public function requisition()
    {
        return $this->hasMany(Requisition::class);
    }

    public function comment()
    {
        return $this->hasMany(Comment::class);
    }

    public function getFullNameAttribute()
    {
        return $this->name . " " . $this->lastname;
    }
    public function getBussineNameAttribute()
    {
        if ($this->bussine_id) {
            return $this->bussine->name;
        }
    }
    public function getAreaNameAttribute()
    {
        if ($this->area_id) {
            return $this->area->name;
        }
    }

    public function getTipoUserAttribute()
    {
        switch ($this->role_id) {
            case '1':
                return 'Administrador';
                break;
            case '2':
                return 'Validación';
                break;
            case '3':
                return 'Preautorizar';
                break;
            case '4':
                return 'Dirección';
                break;
            case '5':
                return 'Compra';
            default:
                return 'Gerente';
        }
    }
    public function getIsAdminAttribute()
    {
        return $this->role_id == 1;
    }
    public function getIsValidationAttribute()
    {
        return $this->role_id == 2;
    }
    public function getIsProcessAttribute()
    {
        return $this->role_id == 2;
    }
    public function getIsPreathorizeAttribute()
    {
        return $this->role_id == 3;
    }
    public function getIsAuthorizeAttribute()
    {
        return $this->role_id == 4;
    }
    public function getIsPaymentAttribute()
    {
        return $this->role_id == 5;
    }
    public function getIsGerenteAttribute()
    {
        return $this->role_id == 6;
    }

    public function activity()
    {
        return $this->hasMany('App\Activity')
            ->with(['user', 'subject'])
            ->latest();
    }
    /**
     * Record new activity for the user.
     *
     * @param  string $name
     * @param  mixed  $related
     * @throws \Exception
     * @return void
     */
    public function recordActivity($name, $related)
    {
        if (! method_exists($related, 'recordActivity')) {
            throw new \Exception('..');
        }
        return $related->recordActivity($name);
    }

    
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\UserRequest;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use App\Mail\NewUser;
use App\Area;
use App\Bussine;
use App\Role;
use App\User;
use Session;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request) {
            $search = trim($request->get('searchText'));
            $users = User::where('name', 'LIKE', '%'.$search.'%')
                            ->orWhere('email', 'LIKE', '%'.$search.'%')
                            ->orderBy('id', 'ASC')
                            ->paginate(10);
        }
        return view('users.index', compact('users','search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        $bussines = Bussine::all();
        $areas = Area::all();
        return view('users.create',compact('roles','bussines','areas'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        $user = new User($request->all());
        $pass = $request->input('password');
        $user->password = bcrypt($request->input('password'));
        $user->avatar = '/images/user.png';
        $user->active = 0;
        if ($request->role_id == 6) {
            $user->selected_bussine_id = $request->bussine_id;
        }
        $user->save();
        Mail::to($user->email)->send(new NewUser($user, $pass));
        Session::flash('success', 'El usuario se ha creado correctamente');
        return redirect('/users');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::findOrFail($id);
        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        $roles = Role::all();
        $bussines = Bussine::all();
        $areas = Area::all();
        return view('users.edit', compact('user','roles','bussines','areas'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
                'name' => 'required|min:2',
                'email' => 'required|email',
                'role_id' => 'required|numeric',
                'bussine_id' => 'required|numeric',
                'area_id'   => 'required|numeric'
            ]
            );
        $user = User::findOrFail($id);
        $user->fill($request->all());
        $user->save();
        Session::flash('success', 'Usuario modificado exitosamente');
        return redirect('/users');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->active = 1;
        $user->save();
        Session::flash('success', 'Usuario desactivado exitosamente');
        return redirect('/users');
    }

    public function getProfile()
    {
        return view('users.profile');
    }
    public function postProfile(Request $request)
    {
        $user = $request->user();
        if($request->file('avatar'))
        {
            $file = $request->file('avatar');
            $name = 'perfil_'. time() . '.' .$file->getClientOriginalExtension();
            $path =  '/images/perfil/';
            $file->move($path, $name);   
        }
        if ($request->get('password') == !null && $request->file('avatar') == !null) {
            
                if(!Hash::check($request->get('current_password'), $user->password))
                {
                return redirect()->back()->withErrors([
                    'current_password' => 'La contreña no es validad'
                    ]);
                }
                $this->validate($request, [
                    'password' => 'required|confirmed',
                    'password_confirmation' => 'required'
                ]);
                $user->where('email', '=', $user->email)->update(['avatar' => '/images/perfil/'.$name, 'password' => bcrypt($request->get('password'))]);
                $user->save();
                return redirect('/users')->with('notification', 'Los cambios se guardaron exitosamente');
        } elseif ($request->get('password') == !null) {
            if(!Hash::check($request->get('current_password'), $user->password))
                {
                return redirect()->back()->withErrors([
                    'current_password' => 'La contreña no es validad'
                    ]);
                }
                $this->validate($request, [
                    'password' => 'required|confirmed',
                    'password_confirmation' => 'required'
                ]);
                $user->where('email', '=', $user->email)->update(['password' => bcrypt($request->get('password'))]);
                $user->save();
                return redirect('/users')->with('notification', 'Los cambios se guardaron exitosamente');
        }
        

        $user->where('email', '=', $user->email)->update(['avatar' => '/images/perfil/'.$name]);
        $user->save();
        Session::flash('success', 'Usuario modificado exitosamente');

        return redirect('/users');
    }
}

resources/views/users/create.blade.php
@extends('layouts.dashboard')
@section('title', 'Creación de usuarios')

@section('content')


<div class="sec_ttls">
  <h2><i class="material-icons">&#xE7FE;</i>Nuevo Usuario</h2>
  <hr>
</div>

<div class="new_user panel panel-primary">
    <div class="panel-heading">Datos del nuevo usuario</div>  
    <div class="panel-body">
        {!! Form::open(['route' => 'users.store'])!!}
        {{ csrf_field()}}

        <div class="row">
            <div class="col-md-6">
                <div class="form-group groups_bottom">
                    <label for="email">Email</label>
                    <input type="email" name="email" class="form-control" value="{{ old('email')}}">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group groups_bottom">
                   <label for="password">Contraseña</label>
                   <input type="text" name="password" class="form-control" value="{{ old('password', str_random(8))}}">
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-6">
                <div class="form-group groups_bottom">
                    <label for="name">Nombre</label>
                    <input type="text" name="name" class="form-control" value="{{ old('name')}}">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group groups_bottom">
                    <label for="lastname">Apellidos</label>
                    <input type="text" name="lastname" class="form-control" value="{{ old('lastname')}}">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group groups_bottom">
                    <label for="address">Dirección</label>
                    <input type="text" name="address" class="form-control" value="{{ old('address')}}">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group groups_bottom">
                    <label for="phone">Teléfono</label>
                    <input type="text" name="phone" class="form-control" value="{{ old('phone')}}">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <div class="form-group groups_bottom">
                   <label for="role_id">Seleccione un rol</label>
                    <select class="form-control" name="role_id">
                        @foreach($roles as $rol)
                        <option value="{{ $rol->id}}">{{ $rol->name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group groups_bottom">
                    <label for="bussine_id">Seleccione una línea de Negocio</label>
                    <select class="form-control" name="bussine_id">
                        @foreach($bussines as $bussine)
                        <option value="{{ $bussine->id}}">{{ $bussine->name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group groups_bottom">
                    <label for="area_id">Seleccione un Área</label>
                    <select class="form-control" name="area_id">
                        @foreach($areas as $area)
                        <option value="{{ $area->id}}">{{ $area->name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>

        <div class="form-group groups_bottom">
            <button class="btn btn-raised btn-success">Registrar</button>
        </div>

        {!! Form::close()!!}
    </div>
</div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.dashboard')
@section('title', 'Edición de usuarios')

@section('content')
<div class="panel panel-primary">
  <div class="panel-heading">
    Editar usuario {{ $user->full_name}}
  </div>  
  <div class="panel-body">
      
    {!! Form::open(['route' => ['users.update', $user], 'method' => 'PUT'])!!}          
    {{ csrf_field()}}

        <div class="row">
            <div class="col-md-12">
                <div class="form-group groups_bottom">
                    <label for="email">Email</label>
                    <input type="email" name="email" class="form-control" value="{{ old('email', $user->email)}}">
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-6">
                <div class="form-group groups_bottom">
                    <label for="name">Nombre</label>
                    <input type="text" name="name" class="form-control" value="{{ old('name',$user->name)}}">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group groups_bottom">
                    <label for="lastname">Apellidos</label>
                    <input type="text" name="lastname" class="form-control" value="{{ old('lastname',$user->lastname)}}">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group groups_bottom">
                    <label for="address">Dirección</label>
                    <input type="text" name="address" class="form-control" value="{{ old('address', $user->address)}}">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group groups_bottom">
                    <label for="phone">Teléfono</label>
                    <input type="text" name="phone" class="form-control" value="{{ old('phone', $user->phone)}}">
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-4">
                <div class="form-group groups_bottom">
                   <label for="role_id">Seleccione un rol</label>
                    <select class="form-control" name="role_id">
                        @foreach($roles as $rol)
                        <option value="{{ $rol->id}}" @if($user->role_id == $rol->id) selected @endif>{{ $rol->name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group groups_bottom">
                    <label for="bussine_id">Seleccione una línea de Negocio</label>
                    <select class="form-control" name="bussine_id">
                        @foreach($bussines as $bussine)
                        <option value="{{ $bussine->id}}" @if($user->bussine_id == $bussine->id) selected @endif>{{ $bussine->name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="col-md-4">
                <div class="form-group groups_bottom">
                    <label for="area_id">Seleccione un Área</label>
                    <select class="form-control" name="area_id">
                        @foreach($areas as $area)
                        <option value="{{ $area->id}}" @if($user->area_id == $area->id) selected @endif>{{ $area->name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
        <div class="form-group">
            <button class="btn btn-raised btn-success">Guardar</button>
        </div>

    {!! Form::close()!!}
</div>
</div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.dashboard')
@section('title', 'Listado de usuarios')

@section('content')

<div class="sec_ttls">
  <h2><i class="material-icons">&#xE7FE;</i> Usuarios</h2>
  <hr>
</div>

<div class="row panel panel-primary sec_toolbar">
  <div class="col-sm-8">
      <a href="/users/create" class="btn btn-raised btn-primary">Nuevo Usuario</a>
  </div>
  <div class="col-sm-4">@include('users.partials.search')</div>
</div>

<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Listado de Usuarios</h3>
  </div>
  <div class="panel-body table-responsive">
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
            <th>Nombre Completo</th>
            <th>Correo</th>
            <th>Tipo de Usuario</th>
            <th>Línea de Negocio</th>
            <th>Área</th>
            <th>Opciones</th>
        </tr>
      </thead>
      <tbody>
        @foreach($users as $user)
        <tr>
            <td>{{$user->full_name}}</td>
            <td>{{$user->email}}</td>
            <td>{{ $user->tipo_user}}</td>
            <td>{{$user->bussine_name}}</td>
            <td>{{ $user->area_name}}</td>
            <td>
              <button class="btn_options ">
                <a href="/users/{{$user->id}}/edit" class="btn-text" data-position="top" data-delay="50" data-tooltip="Cuenta"><i class="material-icons">edit</i>
              </a>
              </button>
              <button class="btn_options">
                <a href="/users/{{ $user->id}}" class=" btn-text" data-position="top" data-delay="50" data-tooltip="Cuenta"><i class="material-icons right">&#xE5D3;</i>
              </a>
              </button>
              
            </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
  <div class=" text-center">
    {{ $users->render()}}
  </div >
</div>

@endsection

resources/views/users/profile.blade.php
@extends('layouts.dashboard')
@section('title', 'Perfil del usuario')

@section('content')

<div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
        <div class="panel-heading">Configurar Perfil</div>
        <div class="panel-body">
        {!! Form::open(['url' =>'/profile','method' => 'POST','enctype' => 'multipart/form-data']) !!}
              {!! csrf_field() !!}
        	<div class="form-group">
			  <input type="file" id="avatar" name="avatar" multiple="">
			  <div class="input-group">
			    <input type="text" readonly="" class="form-control" placeholder="Sube tu foto aquí">
			      <span class="input-group-btn input-group-sm">
			        <button type="button" class="btn btn-fab btn-fab-mini">
			          <i class="material-icons">add_a_photo</i>
			        </button>
			      </span>
			  </div>
			</div>
			<div class="form-group">
				<input type="password" name="current_password" placeholder="Contraseña acutal" class="form-control">
			</div>
			<div class="form-group">
				<input type="password" name="password" placeholder="Nueva Contraseña" class="form-control">
			</div>
			<div class="form-group">
				<input type="password" name="password_confirmation" placeholder="Confirmar Contraseña" class="form-control">
			</div>
			<button class="btn btn-raised btn-primary">Guardar Cambios</button>
           
        {!! Form::close()!!}
        </div>
    </div>
</div>
		
@endsection

resources/views/users/show.blade.php
@extends('layouts.dashboard')
@section('title', 'Creación de usuarios')

@section('content')

<div class="panel panel-primary">
    <div class="panel-heading">Detalles del usuario {{ $user->full_name}}</div>  
    <div class="panel-body">
      <div class="col-md-8">
          <div class="form-group">
            <label for="email">Email:</label>
            {{ $user->email}}
          </div>
          <div class="form-group">
            <label for="name">Nombre:</label>
            {{ $user->name}}
          </div>
          <div class="form-group">
            <label for="lastname">Apellidos:</label>
            {{$user->lastname}}
          </div>
          <div class="form-group">
            <label for="address">Dirección:</label>
            {{$user->address}}
          </div>
          <div class="form-group">
            <label for="phone">Teléfono:</label>
            {{$user->phone}}
          </div>
          
          <div class="form-group">
            <label for="role_id">Rol:</label>
            {{ $user->tipo_user}}
          </div>
          <div class="form-group">
            <label for="bussine_id">Línea de Negocio:</label>
            {{$user->bussine_name}}
          </div>
          <div class="form-group">
            <label for="area_id">Área:</label>
            {{$user->area_name}}
          </div>
      </div>
      <div class="col-md-4 text-center">
        <img class="circle_avatar2" src="{{ Auth::user()->avatar}}" alt="avatar">
      </div>

 
    </div>
</div>



 
@endsection