routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/requisiciones', function () {
    return view('/home');
});

Route::get('/requisiciones', 'RequisitionController@index');

// inyección de dependencias en Compañias
Route::bind('company', function($company){
	return App\Company::find($company);
});

// inyección de dependencias en Empresas
Route::bind('bussine', function($bussine){
	return App\Bussine::find($bussine);
});

// inyección de dependencias en areas
Route::bind('area', function($area){
	return App\Area::find($area);
});

// inyección de dependencias en proveedores
Route::bind('provider', function($provider){
	return App\Provider::find($provider);
});

Route::get('get_unread', function() {
	return Auth::user()->unreadNotifications;
});

Route::get('/notifications', 'HomeController@notifications');

Auth::routes();
Route::group(['middleware' => 'auth'], function (){

	Route::get('/home', 'HomeController@index');
	Route::resource('/company', 'CompanyController');
	Route::resource('product', 'ProductController');
	Route::get('product/subcategory/{id}', 'ProductController@getCategory');
	Route::resource('/bussine', 'BussineController');
	Route::resource('/area', 'AreaController');
	Route::resource('/provider', 'ProviderController');
	//add routes for users crud
	Route::resource('users', 'UserController');
	Route::get('/profile', 'UserController@getProfile');
	Route::post('/profile', 'UserController@postProfile'); 
	//add routes for categories crud
	Route::resource('categories', 'CategoryController');
	//add routes for subcategories crud
	Route::resource('subcategories', 'SubCategoryController');
	//add routes for requisitions crud
	Route::resource('requisitions', 'RequisitionController');
	Route::get('/api/requisitions/{id}/providers', 'RequisitionController@getProviders');
	Route::get('bussines/{id}', 'RequisitionController@getBussine');
	Route::get('requisitions/subcategory/{id}', 'RequisitionController@getCategory');
	//add routes for status change
	Route::get('requisitions/{id}/validate', 'RequisitionController@validacion');
	Route::get('requisitions/{id}/preauthorize', 'RequisitionController@preauthorize');
	Route::get('requisitions/{id}/authorizar', 'RequisitionController@authorization');
	Route::get('requisitions/{id}/process', 'RequisitionController@process');
	Route::get('requisitions/{id}/payment', 'RequisitionController@payment');
	Route::get('requisitions/{id}/rejected', 'RequisitionController@rejected');
	Route::get('requisitions/{id}/finalizadas', 'RequisitionController@finalizadas');
	Route::post('requisitions/uploadticket', [
		'uses' => 'RequisitionController@uploadticket',
		'as' 	=> 'requisitions.uploadticket'
		]);
	Route::post('requisitions/uploadvoucher', [
		'uses' => 'RequisitionController@uploadvoucher',
		'as' 	=> 'requisitions.uploadvoucher'
		]);
	//routes for comments
	Route::get('/api/requisitions/{requisition}/comments', 'CommentController@index');
	Route::post('/api/requisitions/{requisition}/comment', 'CommentController@store');
	//add routes for select bssines
	Route::get('select/bussine/{id}', 'RequisitionController@selectBussine');
	//add routes for export excel report
	Route::get('/reports-general', 'ExcelController@index');
	Route::post('/search-reports', [
		'uses' => 'ExcelController@search',
		'as' => 'searchreport.store'
		]);
	//reports requisition print
	Route::get('/export-requisition/{id}/print', 'ExcelController@exportRequisition');
	//activities
	Route::get('/activities', 'ActivityController@viewActivity');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
	protected $table = "categories";
    protected $fillable = [
        'name'
    ];
        public function subcategory()
    {
        return $this->hasMany(SubCategory::class);
    }
}

app/DetailRequisition.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DetailRequisition extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = "details_requisitions";
    protected $fillable = [
        'product_id', 'quantity', 'unity','iva','price','observations','riquisition_id','category_id', 'subcategory_id'
    ];

    public function requisition()
    {
        return $this->belongsTo(Requisition::class);
    }
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function subcategory()
    {
        return $this->belongsTo(SubCategory::class);
    }

    public function getCategoryNameAttribute()
    {
        if ($this->category_id) {
            return $this->category->name;
        }
        return;
    }
    public function getSubcategoryNameAttribute()
    {
        if ($this->subcategory_id) {
            return $this->subcategory->name;
        }
        return;
    }

    public function getTipoPagoAttribute()
    {
        switch ($this->type_payment) {
            case '0':
                return 'Efectivo';
                break;
            case '1':
                return 'Cheque';
                break;
	    case '2':
                return 'Transferencia';
                break;
            default:
                return 'Pago en linea';
                break;
        }
    }

}

app/SubCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SubCategory extends Model
{
    protected $table = "types_categories";
    protected $fillable = [
        'name','category_id'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    
    public static function subcategory($id){
        return SubCategory::where('category_id','=',$id)->get();
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\SubCategory;
use Session;
class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request) {
            $search = trim($request->get('searchText'));
            $categories = Category::where('name', 'LIKE', '%'.$search.'%')
                            ->orderBy('id', 'ASC')
                            ->paginate(10);
        }
        return view('categories.index', compact('categories','search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function subcategories(Request $request)
    {
        if ($request) {
            $search = trim($request->get('searchText'));
            $categories = SubCategory::where('name', 'LIKE', '%'.$search.'%')
                            ->orderBy('id', 'ASC')
                            ->paginate(10);
        }
        return view('categories.index', compact('categories','search'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
                'name' => 'required|min:2',
            ]
            );
        $category = new Category($request->all());
        $category->save();

        Session::flash('success', 'La categoria se ha creado exitosamente');

        return redirect('/categories');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::findOrFail($id);
        return response()->json(
                $category->toArray()
            );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);
        $category->fill($request->all());
        $category->save();

        return response()->json([
                'message' => 'listo'
            ]);
        
    }

    public function getUpdate(Request $request)
    {
        if ($request->ajax()) {
            $category = Category::findOrFail($request->id);
            return response($category);
        }
    }

    public function newUpdate(Request $request)
    {
        if ($request->ajax()) {
            $category = Category::findOrFail($request->id);
            $category->name = $request->name;
            $category->save();
            return response($category);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/SubCategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\SubCategory;
use App\Category;
use Session;
class SubCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request) {
            $search = trim($request->get('searchText'));
            $subcategories = SubCategory::where('name', 'LIKE', '%'.$search.'%')
                            ->orderBy('id', 'ASC')
                            ->paginate(10);
            
        }
        $categories = Category::all();
        return view('categories.subcategories.index', compact('subcategories','search', 'categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $category = SubCategory::findOrFail($id);
        return response()->json(
                $subcategory->toArray()
            );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
                'name' => 'required|min:3',
                ]
            );
        $subcategory = new SubCategory($request->all());
        $subcategory->save();
        Session::flash('success', 'La subcategoria se ha creado exitosamente');
        return redirect('/subcategories');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $subcategory = SubCategory::findOrFail($id);
        return response()->json(
                $subcategory->toArray()
            );
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $subcategory = SubCategory::findOrFail($id);
        $subcategory->fill($request->all());
        $subcategory->save();

        return response()->json([
                'message' => 'listo'
            ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/categories/subcategories/create.blade.php
{!! Form::open(['route' => 'subcategories.store'])!!}
{{ csrf_field()}}
<div class="modal" id="simple-dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Crear Nueva Sub-categoria</h4>
      </div>
      <div class="modal-body">
        <label for="name">Nombre de la categoria</label>
         <input type="text" name="name" class="form-control" value="{{ old('name')}}" placeholder="Escribe la sub-categoria..">
             <label>Selecciona una categoria</label>

         <select name="category_id" class="form-control selectpicker" data-live-search="true">
      @foreach($categories as $category)
        <option value="{{$category->id}}" >{{ $category->name}}</option>
        @endforeach
    </select>
      </div>
      <div class="modal-footer">
        <button  class="btn btn-raised btn-danger" data-dismiss="modal">Cancelar</button>
        <button  class="btn btn-raised btn-success">Guardar</button>
      </div>
    </div>
  </div>
</div>

{!! Form::close()!!}

resources/views/categories/subcategories/edit.blade.php
<div class="modal" id="edit-sub">
    <div class="modal-dialog" id="cerrar">
        <div class="modal-content">
            <div class="modal-header">
                <button  class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Editar Categoria {{ $sub->name}}</h4>
            </div>
            <div class="modal-body">
                    <input type="hidden" name="_token" value="{{ csrf_token()}}" id="token">
                    <input type="hidden" id="id" value="{{ $sub->id}}">
              <div class="form-group">
                  <h4>Editar la subcategoria {{ $sub->name}}</h4>
                  <label for="name">Nombre de la subcategoria</label>
                  <input type="text" name="name" id="name" class="form-control" value="{{ old('name', $sub->name)}}" placeholder="Escribe la categoria..">
              </div>
              <div class="form-group">
                <label>Selecciona una categoria</label>
                  <select class="form-control selectpicker" name="category_id" id="category_selected">
                      @foreach($categories as $category)
                      <option value="{{$category->id}}" @if($sub->category_id == $category->id) selected @endif >{{ $category->name}}</option>
                      @endforeach
                  </select>
              </div>
              <div class="modal-footer">
                <button  class="btn btn-primary" id="actualizar-sub">Guardar</button>
            </div>
        </div>
    </div>
</div>

resources/views/categories/subcategories/index.blade.php
@extends('layouts.dashboard')
@section('title', 'Lista de Categorias')

@section('content')
<div class="alert alert-dismissible alert-success" id="msj-success" style="display: none">
  <button type="button" class="close" data-dismiss="alert">×</button>
  <strong>Sub-categoria editada con éxito</strong>
</div>

<div class="sec_ttls">
	<h2><i class="material-icons">&#xE8E7;</i> Subcategorías</h2>
	<hr>
</div>

<div class="row panel panel-primary sec_toolbar">
	<div class="col-sm-8">
		<button type="button" class="btn btn-raised btn-primary" data-toggle="modal" data-target="#simple-dialog">Nueva Subcategoría</button>
		  @include('categories.subcategories.create')
	</div>
	<div class="col-sm-4">@include('categories.subcategories.search')</div>
</div>

<div class="panel panel-primary">
	<div class="panel-heading">
		<h3 class="panel-title">Listado de Categorías</h3>
	</div>
	<div class="panel-body table-responsive">
		<table class="table table-striped table-bordered table-hover">
			<thead>
				<tr>
					<th class="text-center">#</th>
					<th>Nombre Completo</th>
					<th>Categoría</th>
					<th>Opciones</th>
				</tr>
			</thead>
			<tbody>
			@foreach($subcategories as $sub)
				<tr>
					<td class="text-center">{{ $sub->id}}</td>
					<td>{{ $sub->name}}</td>
					<td>{{ $sub->category_name}}</td>
					<td>
					
						<button class="btn_options btn-text" data-toggle="modal" data-target="#edit-sub" OnClick="mostrarSub(this);" value="{{ $sub->id}}"><i class="material-icons">edit</i></button>
						{{-- <a href="categories/{{$category->id}}/destroy" class="btn_options btn-text"><i class="material-icons">delete</i></a> --}}
					
					</td>
				</tr>
				<tr>
				@include('categories.subcategories.edit')
			@endforeach
			</tbody>
		</table>
	</div>
	<div  class=" text-center">
		{{ $subcategories->render()}}
	</div >
</div>


@endsection

resources/views/categories/subcategories/search.blade.php
{!! Form::open(array('url' =>'subcategories', 'method' => 'GET', 'autocomplete' => 'off', 'role' => 'search'))!!}

	<div class="form-group">
		<div class="input-group">
			<input type="text" name="searchText" class="form-control" value="{{ old('searchText')}}" placeholder="Buscar Subcategoría...">
			<span class="input-group-btn">
				<button type="submit" class="btn btn-raised btn-primary"><span class="glyphicon glyphicon-search"></span></button>
			</span>
		</div>
          	
    </div>
      
{!! Form::close()!!}