routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/requisiciones', function () {
    return view('/home');
});

Route::get('/requisiciones', 'RequisitionController@index');

// inyección de dependencias en Compañias
Route::bind('company', function($company){
	return App\Company::find($company);
});

// inyección de dependencias en Empresas
Route::bind('bussine', function($bussine){
	return App\Bussine::find($bussine);
});

// inyección de dependencias en areas
Route::bind('area', function($area){
	return App\Area::find($area);
});

// inyección de dependencias en proveedores
Route::bind('provider', function($provider){
	return App\Provider::find($provider);
});

Route::get('get_unread', function() {
	return Auth::user()->unreadNotifications;
});

Route::get('/notifications', 'HomeController@notifications');

Auth::routes();
Route::group(['middleware' => 'auth'], function (){

	Route::get('/home', 'HomeController@index');
	Route::resource('/company', 'CompanyController');
	Route::resource('product', 'ProductController');
	Route::get('product/subcategory/{id}', 'ProductController@getCategory');
	Route::resource('/bussine', 'BussineController');
	Route::resource('/area', 'AreaController');
	Route::resource('/provider', 'ProviderController');
	//add routes for users crud
	Route::resource('users', 'UserController');
	Route::get('/profile', 'UserController@getProfile');
	Route::post('/profile', 'UserController@postProfile'); 
	//add routes for categories crud
	Route::resource('categories', 'CategoryController');
	//add routes for subcategories crud
	Route::resource('subcategories', 'SubCategoryController');
	//add routes for requisitions crud
	Route::resource('requisitions', 'RequisitionController');
	Route::get('/api/requisitions/{id}/providers', 'RequisitionController@getProviders');
	Route::get('bussines/{id}', 'RequisitionController@getBussine');
	Route::get('requisitions/subcategory/{id}', 'RequisitionController@getCategory');
	//add routes for status change
	Route::get('requisitions/{id}/validate', 'RequisitionController@validacion');
	Route::get('requisitions/{id}/preauthorize', 'RequisitionController@preauthorize');
	Route::get('requisitions/{id}/authorizar', 'RequisitionController@authorization');
	Route::get('requisitions/{id}/process', 'RequisitionController@process');
	Route::get('requisitions/{id}/payment', 'RequisitionController@payment');
	Route::get('requisitions/{id}/rejected', 'RequisitionController@rejected');
	Route::get('requisitions/{id}/finalizadas', 'RequisitionController@finalizadas');
	Route::post('requisitions/uploadticket', [
		'uses' => 'RequisitionController@uploadticket',
		'as' 	=> 'requisitions.uploadticket'
		]);
	Route::post('requisitions/uploadvoucher', [
		'uses' => 'RequisitionController@uploadvoucher',
		'as' 	=> 'requisitions.uploadvoucher'
		]);
	//routes for comments
	Route::get('/api/requisitions/{requisition}/comments', 'CommentController@index');
	Route::post('/api/requisitions/{requisition}/comment', 'CommentController@store');
	//add routes for select bssines
	Route::get('select/bussine/{id}', 'RequisitionController@selectBussine');
	//add routes for export excel report
	Route::get('/reports-general', 'ExcelController@index');
	Route::post('/search-reports', [
		'uses' => 'ExcelController@search',
		'as' => 'searchreport.store'
		]);
	//reports requisition print
	Route::get('/export-requisition/{id}/print', 'ExcelController@exportRequisition');
	//activities
	Route::get('/activities', 'ActivityController@viewActivity');
});

app/Requisition.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Requisition extends Model
{

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = "requisitions";
    protected $fillable = [
        'folio', 'title', 'description','status','archive_payment','archive_ticket','total','fechadepago','area_id','bussine_id','manager_id','user_id','provider_id','date_programming','validation_id','preathorize_id','authorize_id','payment_id','rejected_id','finish_id'
    ];

    public function area()
    {
        return $this->belongsTo(Area::class);
    }

     public function product()
    {
        return $this->belongsTo(Products::class);
    }

    public function company()
    {
        return $this->belongsTo(Company::class);
    }

    public function bussine()
    {
        return $this->belongsTo(Bussine::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function validation()
    {
        return $this->belongsTo(User::class, 'validation_id');
    }

    public function preauthorization()
    {
        return $this->belongsTo(User::class, 'preauthorize_id');
    }
    public function authorization()
    {
        return $this->belongsTo(User::class, 'authorize_id');
    }
    public function payment()
    {
        return $this->belongsTo(User::class, 'payment_id');
    }
    public function rejected()
    {
        return $this->belongsTo(User::class, 'rejected_id');
    }
    /*public function finish()
    {
        return $this->belongsTo(User::class, 'finish_id');
    }*/
    public function archives()
    {
        return $this->hasMany(ArchiveRequisition::class);
    }
    public function provider()
    {
        return $this->belongsTo(Provider::class);
    }
    public function detallerequisition()
    {
        return $this->belongsTo(DetailRequisition::class);
    }

    public function archiveRequisition()
    {
        return $this->hasMany(ArchiveRequisition::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class);
    }

    public function getStateAttribute()
    {
        switch ($this->status) {
            case '0':
                return 'En validación';
                break;
            case '1':
                return 'En espera pre-autorización';
                break;
            case '2':
                return 'Pre-autorizada';
                break;
            case '3':
                return 'Autorizada';
                break;
            case '4':
                return 'Proceso de pago';
                break;
            case '5':
                return 'Pagada';
                break;
            case '6':
                return 'Rechazada';
                break;
            default:
                return 'Finalizada';
        }
    }

    public function getBussineNameAttribute()
    {
        if ($this->bussine_id) {
            return $this->bussine->name;
        }
        return;
    }
    public function getCompanyNameAttribute()
    {
        if ($this->company_id) {
            return $this->company->name;
        }
        return;
    }
    public function getUserNameAttribute()
    {
        if ($this->user_id) {
            return $this->user->name . " " . $this->user->lastname;
        }
        return;
    }
    public function getAreaNameAttribute()
    {
        if ($this->area_id) {
            return $this->area->name;
        }
        return;
    }
    public function getProviderNameAttribute()
    {
        if ($this->provider_id) {
            return $this->provider->name;
        }
        return;
    }
    public function getProviderAddressAttribute()
    {
        if ($this->provider_id) {
            return $this->provider->address;
        }
        return;
    }
    public function getProviderRfcAttribute()
    {
        if ($this->provider_id) {
            return $this->provider->rfc;
        }
        return;
    }
    public function getValidationNameAttribute()
    {
        if ($this->validation) {
            return $this->validation->name . " ". $this->validation->lastname;
        }
        return;
    }
    
    public function getpreauthorizeNameAttribute()
    {
        if ($this->preauthorization) {
            return $this->preauthorization->name . " ". $this->preauthorization->lastname;
        }
        return;
    }
    public function getauthorizeNameAttribute()
    {
        if ($this->authorization) {
            return $this->authorization->name . " ". $this->authorization->lastname;
        }
        return;
    }
    public function getPaymentNameAttribute()
    {
        if ($this->payment) {
            return $this->payment->name . " ". $this->payment->lastname;
        }
        return;
    }
    public function getRejectedNameAttribute()
    {
        if ($this->rejected) {
            return $this->rejected->name . " ". $this->rejected->name;
        }
        return;
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [

        'name', 'email', 'password','lastname','address','phone','role','role_id','bussine_id','area_id'
    ];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function bussine()
    {
        return $this->belongsTo(Bussine::class);
    }

    public function area()
    {
        return $this->belongsTo(Area::class);
    }

    public function requisition()
    {
        return $this->hasMany(Requisition::class);
    }

    public function comment()
    {
        return $this->hasMany(Comment::class);
    }

    public function getFullNameAttribute()
    {
        return $this->name . " " . $this->lastname;
    }
    public function getBussineNameAttribute()
    {
        if ($this->bussine_id) {
            return $this->bussine->name;
        }
    }
    public function getAreaNameAttribute()
    {
        if ($this->area_id) {
            return $this->area->name;
        }
    }

    public function getTipoUserAttribute()
    {
        switch ($this->role_id) {
            case '1':
                return 'Administrador';
                break;
            case '2':
                return 'Validación';
                break;
            case '3':
                return 'Preautorizar';
                break;
            case '4':
                return 'Dirección';
                break;
            case '5':
                return 'Compra';
            default:
                return 'Gerente';
        }
    }
    public function getIsAdminAttribute()
    {
        return $this->role_id == 1;
    }
    public function getIsValidationAttribute()
    {
        return $this->role_id == 2;
    }
    public function getIsProcessAttribute()
    {
        return $this->role_id == 2;
    }
    public function getIsPreathorizeAttribute()
    {
        return $this->role_id == 3;
    }
    public function getIsAuthorizeAttribute()
    {
        return $this->role_id == 4;
    }
    public function getIsPaymentAttribute()
    {
        return $this->role_id == 5;
    }
    public function getIsGerenteAttribute()
    {
        return $this->role_id == 6;
    }

    public function activity()
    {
        return $this->hasMany('App\Activity')
            ->with(['user', 'subject'])
            ->latest();
    }
    /**
     * Record new activity for the user.
     *
     * @param  string $name
     * @param  mixed  $related
     * @throws \Exception
     * @return void
     */
    public function recordActivity($name, $related)
    {
        if (! method_exists($related, 'recordActivity')) {
            throw new \Exception('..');
        }
        return $related->recordActivity($name);
    }

    
}

resources/views/requisitions/partials/create-product.blade.php
{!! Form::open(['route' => 'product.store'])!!}
{{ csrf_field()}}
<div class="modal" id="create-product">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Crear Nuevo Producto</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                   <label for="name">Nombre del Producto</label>
                   <input type="text" name="name" class="form-control" value="{{ old('name')}}" placeholder="Escribe el nombre">
               </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-raised btn-danger" data-dismiss="modal">Cancelar</button>
                <button class="btn btn-raised btn-success">Guardar</button>
                
            </div>
        </div>
    </div>
</div>

{!! Form::close()!!}

resources/views/requisitions/partials/create-provider.blade.php
{!! Form::open(['route' => 'provider.store']) !!}
{{ csrf_field()}}
<div class="modal" id="create-provider">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Crear Nuevo Proveedor</h4>
            </div>
            <div class="modal-body">
                <div class="form-group">
                   <label for="name">Nombre del Proveedor</label>
                   <input type="text" name="name" class="form-control" value="{{ old('name')}}" placeholder="Escribe el nombre">
               </div>
               <div class="form-group">
                   <label for="address">Dirección</label>
                   <input type="text" name="address" class="form-control" value="{{ old('address')}}" placeholder="Escribe la dirección">
               </div>
               <div class="form-group">
                   <label for="rfc">RFC</label>
                   <input type="text" name="rfc" class="form-control" value="{{ old('rfc')}}" placeholder="Escribe el RFC..">
               </div>
               <div class="form-group">
                   <label for="phone">Telefono</label>
                   <input type="text" name="phone" class="form-control" value="{{ old('phone')}}" placeholder="Escribe el phone..">
               </div>
               <div class="form-group">
                   <label for="email">Email</label>
                   <input type="email" name="email" class="form-control" value="{{ old('email')}}" placeholder="Escribe el RFC..">
               </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-raised btn-danger" data-dismiss="modal">Cancelar</button>
                <button class="btn btn-raised btn-success">Guardar</button>
                
            </div>
        </div>
    </div>
</div>

{!! Form::close()!!}

resources/views/requisitions/partials/nextstatus.blade.php
@if(auth()->user()->is_validation && $requisition->status == 0)
    <div class="col-md-2">
        <a href="/requisitions/{{ $requisition->id}}/validate" class="btn btn-raised btn-success">Validar</a>
    </div>
    <div class="col-md-2">
        <a href="/requisitions/{{ $requisition->id}}/rejected" class="btn btn-raised btn-danger">Rechazar</a>
    </div>
@endif
@if(auth()->user()->is_preathorize && $requisition->status == 1)
    <div class="col-md-2">
        <a href="/requisitions/{{ $requisition->id}}/preauthorize" class="btn btn-raised btn-success">Pre-autorizar</a>
    </div>
    <div class="col-md-2">
        <a href="/requisitions/{{ $requisition->id}}/rejected" class="btn btn-raised btn-danger">Rechazar</a>
    </div>
@endif
@if(auth()->user()->is_authorize && $requisition->status == 2)
    <div class="col-md-2">
        <a href="/requisitions/{{ $requisition->id}}/authorizar" class="btn btn-raised btn-success">Autorizar</a>
    </div>
    <div class="col-md-2">
        <a href="/requisitions/{{ $requisition->id}}/rejected" class="btn btn-raised btn-danger">Rechazar</a>
    </div>
@endif

@if(auth()->user()->is_process && $requisition->status == 3)
    <div class="col-md-2">
        <a href="/requisitions/{{ $requisition->id}}/process" class="btn btn-raised btn-success">Proceso Pago</a>
    </div>
@endif
@if(auth()->user()->is_payment && $requisition->status == 4)
{!! Form::open(['route'=>'requisitions.uploadticket','method'=>'POST','enctype' => 'multipart/form-data', 'id' => 'addTicket','class' =>'dropzone' ]) !!}
    <input type="hidden" name="requisition_id" value="{{ $requisition->id }}">
   
{!! Form::close()!!}
    <div class="col-md-2">
        <a href="/requisitions/{{ $requisition->id}}/payment" class="btn btn-raised btn-success" id="payment">Pagar</a>
    </div>
    
@endif

@if(auth()->user()->role_id ==6 || auth()->user()->role_id ==8 || auth()->user()->role_id ==7 && $requisition->status == 5 && $requisition->user_id == auth()->user()->id)
{!! Form::open(['route'=>'requisitions.uploadvoucher','method'=>'POST','enctype' => 'multipart/form-data', 'id' => 'addVoucher','class' =>'dropzone' ]) !!}
    <input type="hidden" name="requisition_id" value="{{ $requisition->id }}">
   
{!! Form::close()!!}
    <div class="col-md-2">
        <a href="/requisitions/{{ $requisition->id}}/finalizadas" class="btn btn-raised btn-primary" id="voucher">Finalizar</a>
    </div>
@endif
@if(auth()->user()->is_validation  && $requisition->status == 5 && $requisition->user_id == auth()->user()->id )
{!! Form::open(['route'=>'requisitions.uploadvoucher','method'=>'POST','enctype' => 'multipart/form-data', 'id' => 'addVoucher','class' =>'dropzone' ]) !!}
    <input type="hidden" name="requisition_id" value="{{ $requisition->id }}">
   
{!! Form::close()!!}
    <div class="col-md-2">
        <a href="/requisitions/{{ $requisition->id}}/finalizadas" class="btn btn-raised btn-primary" id="voucher">Finalizar</a>
    </div>
@endif
@if(auth()->user()->is_preathorize  && $requisition->status == 5 && $requisition->user_id == auth()->user()->id )
{!! Form::open(['route'=>'requisitions.uploadvoucher','method'=>'POST','enctype' => 'multipart/form-data', 'id' => 'addVoucher','class' =>'dropzone' ]) !!}
    <input type="hidden" name="requisition_id" value="{{ $requisition->id }}">
   
{!! Form::close()!!}
    <div class="col-md-2">
        <a href="/requisitions/{{ $requisition->id}}/finalizadas" class="btn btn-raised btn-primary" id="voucher">Finalizar</a>
    </div>
@endif
@if($requisition->status == 3 || $requisition->status == 0 || $requisition->status == 1 || $requisition->status == 2 || $requisition->status == 4 || $requisition->status == 5 || $requisition->status == 6 || $requisition->status == 7)
<div class="col-md-2">
    <a href="/export-requisition/{{ $requisition->id}}/print" class="btn btn-raised btn-primary" target="_blank">
        @if($requisition->status == 3 || $requisition->status == 0 || $requisition->status == 1 || $requisition->status == 2 || $requisition->status == 4 || $requisition->status == 5 || $requisition->status == 6 || $requisition->status == 7)
        Imprimir
        @else 
        Solicitud de pago
        @endif
    </a>
</div>
@endif

resources/views/requisitions/partials/table-authorize.blade.php
<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>Folio</th>
    <th>Fecha de creación</th>
    <th>Concepto</th>
    <th>Fecha programada de pago</th>
    <th>Total</th>
    <th>Status</th>
    <th>Empresa</th>
    <th>Detalles</th>
  </tr>
  </thead>
  <tbody>
  <tr>
  @foreach ($authorizes as $pre)
    <td>{{$pre->folio}}</td>
    <td>{{$pre->created_at}}</td>
    <td>{{$pre->title}}</td>
    <td>{{$pre->date_programming}}</td>
    <td>${{ number_format($pre->total, 2)}}</td>
    <td>{{$pre->state}}</td>
    <td>{{ $pre->bussine_name}}</td>
    <td><a href="{{ route('requisitions.show', $pre) }}">
          <i class="btn_detalles material-icons">&#xE5D3;</i>
          
        </a>
    </td>
  </tr>
  @endforeach
  </tbody>
</table>

resources/views/requisitions/partials/table-finish.blade.php
<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>Folio</th>
    <th>Fecha de creación</th>
    <th>Concepto</th>
    <th>Fecha programada de pago</th>
    <th>Total</th>
    <th>Status</th>
    <th>Empresa</th>
  </tr>
  </thead>
  <tbody>
  <tr>
  @foreach ($finalizadas as $pre)
    <td>{{$pre->folio}}</td>
    <td>{{$pre->created_at}}</td>
    <td>{{$pre->title}}</td>
    <td>{{$pre->date_programming}}</td>
    <td>${{ number_format($pre->total, 2)}}</td>
    <td>{{$pre->state}}</td>
    <td>{{ $pre->bussine_name}}</td>
    <td><a href="{{ route('requisitions.show', $pre) }}">
          <i class="btn_detalles material-icons">&#xE5D3;</i>
        </a>
    </td>
  </tr>
  @endforeach
  </tbody>
</table>

resources/views/requisitions/partials/table-paid.blade.php
<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>Folio</th>
    <th>Fecha de creación</th>
    <th>Concepto</th>
    <th>Fecha programada de pago</th>
    <th>Total</th>
    <th>Status</th>
    <th>Empresa</th>
  </tr>
  </thead>
  <tbody>
  <tr>
  @foreach ($payments as $pre)
    <td>{{$pre->folio}}</td>
    <td>{{$pre->created_at}}</td>
    <td>{{$pre->title}}</td>
    <td>{{$pre->date_programming}}</td>
    <td>${{ number_format($pre->total, 2)}}</td>
    <td>{{$pre->state}}</td>
    <td>{{ $pre->bussine_name}}</td>
    <td><a href="{{ route('requisitions.show', $pre) }}">
          <i class="btn_detalles material-icons">&#xE5D3;</i>
          
        </a>
    </td>
  </tr>
  @endforeach
  </tbody>
</table>

resources/views/requisitions/partials/table-payment.blade.php
<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>Folio</th>
    <th>Fecha de creación</th>
    <th>Concepto</th>
    <th>Fecha programada de pago</th>
    <th>Total</th>
    <th>Status</th>
    <th>Empresa</th>
  </tr>
  </thead>
  <tbody>
  <tr>
  @foreach ($enpayments as $pre)
    <td>{{$pre->folio}}</td>
    <td>{{$pre->created_at}}</td>
    <td>{{$pre->title}}</td>
    <td>{{$pre->date_programming}}</td>
    <td>${{ number_format($pre->total, 2)}}</td>
    <td>{{$pre->state}}</td>
    <td>{{ $pre->bussine_name}}</td>
    <td><a href="{{ route('requisitions.show', $pre) }}">
          <i class="btn_detalles material-icons">&#xE5D3;</i>
          
        </a>
    </td>
  </tr>
  @endforeach
  </tbody>
</table>

resources/views/requisitions/partials/table-pre-authorize.blade.php
<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>Folio</th>
    <th>Fecha de creación</th>
    <th>Concepto</th>
    <th>Fecha programada de pago</th>
    <th>Total</th>
    <th>Status</th>
    <th>Empresa</th>
  </tr>
  </thead>
  <tbody>
  <tr>
  @foreach ($preauthorizes as $pre)
    <td>{{$pre->folio}}</td>
    <td>{{$pre->created_at}}</td>
    <td>{{$pre->title}}</td>
    <td>{{$pre->date_programming}}</td>
    <td>${{ number_format($pre->total, 2)}}</td>
    <td>{{$pre->state}}</td>
    <td>{{ $pre->bussine_name}}</td>
    <td><a href="{{ route('requisitions.show', $pre) }}">
          <i class="btn_detalles material-icons">&#xE5D3;</i>
          
        </a>
    </td>
  </tr>
  @endforeach
  </tbody>
</table>

resources/views/requisitions/partials/table-rejected.blade.php
<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>Folio</th>
    <th>Fecha de creación</th>
    <th>Concepto</th>
    <th>Fecha programada de pago</th>
    <th>Total</th>
    <th>Status</th>
    <th>Empresa</th>
  </tr>
  </thead>
  <tbody>
  <tr>
  @foreach ($rejecteds as $pre)
    <td>{{$pre->folio}}</td>
    <td>{{$pre->created_at}}</td>
    <td>{{$pre->title}}</td>
    <td>{{$pre->date_programming}}</td>
    <td>${{ number_format($pre->total, 2)}}</td>
    <td>{{$pre->state}}</td>
    <td>{{ $pre->bussine_name}}</td>
    <td><a href="{{ route('requisitions.show', $pre) }}">
          <i class="btn_detalles material-icons">&#xE5D3;</i>
          
        </a>
    </td>
  </tr>
  @endforeach
  </tbody>
</table>

resources/views/requisitions/partials/table-validation.blade.php
<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>Folio</th>
    <th>Fecha de creación</th>
    <th>Concepto</th>
    <th>Fecha programada de pago</th>
    <th>Total</th>
    <th>Status</th>
    <th>Empresa</th>
    <th>Detalles</th>
  </tr>
  </thead>
  <tbody>
  <tr>
  @foreach ($validations as $requisition)
    <td>{{$requisition->folio}}</td>
    <td>{{$requisition->created_at}}</td>
    <td>{{$requisition->title}}</td>
    <td>{{$requisition->date_programming}}</td>
    <td>${{ number_format($requisition->total, 2)}}</td>
    <td>{{$requisition->state}}</td>
    <td>{{ $requisition->bussine_name}}</td>
    <td><a href="{{ route('requisitions.show', $requisition) }}">
          <i class="btn_detalles material-icons">&#xE5D3;</i>
        </a>
    </td>
  </tr>
  @endforeach
  </tbody>
</table>

resources/views/requisitions/partials/table-wait.blade.php
<table class="table table-striped table-hover ">
  <thead>
  <tr>
    <th>Folio</th>
    <th>Fecha de creación</th>
    <th>Concepto</th>
    <th>Fecha programada de pago</th>
    <th>Total</th>
    <th>Status</th>
    <th>Empresa</th>
  </tr>
  </thead>
  <tbody>
  <tr>
  @foreach ($enpreauthorizes as $pre)
    <td>{{$pre->folio}}</td>
    <td>{{$pre->created_at}}</td>
    <td>{{$pre->title}}</td>
    <td>{{$pre->date_programming}}</td>
    <td>${{ number_format($pre->total, 2)}}</td>
    <td>{{$pre->state}}</td>
    <td>{{ $pre->bussine_name}}</td>
    <td><a href="{{ route('requisitions.show', $pre) }}">
          <i class="btn_detalles material-icons">&#xE5D3;</i>
          
        </a>
    </td>
  </tr>
  @endforeach
  </tbody>
</table>