routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/requisiciones', function () {
    return view('/home');
});

Route::get('/requisiciones', 'RequisitionController@index');

// inyección de dependencias en Compañias
Route::bind('company', function($company){
	return App\Company::find($company);
});

// inyección de dependencias en Empresas
Route::bind('bussine', function($bussine){
	return App\Bussine::find($bussine);
});

// inyección de dependencias en areas
Route::bind('area', function($area){
	return App\Area::find($area);
});

// inyección de dependencias en proveedores
Route::bind('provider', function($provider){
	return App\Provider::find($provider);
});

Route::get('get_unread', function() {
	return Auth::user()->unreadNotifications;
});

Route::get('/notifications', 'HomeController@notifications');

Auth::routes();
Route::group(['middleware' => 'auth'], function (){

	Route::get('/home', 'HomeController@index');
	Route::resource('/company', 'CompanyController');
	Route::resource('product', 'ProductController');
	Route::get('product/subcategory/{id}', 'ProductController@getCategory');
	Route::resource('/bussine', 'BussineController');
	Route::resource('/area', 'AreaController');
	Route::resource('/provider', 'ProviderController');
	//add routes for users crud
	Route::resource('users', 'UserController');
	Route::get('/profile', 'UserController@getProfile');
	Route::post('/profile', 'UserController@postProfile'); 
	//add routes for categories crud
	Route::resource('categories', 'CategoryController');
	//add routes for subcategories crud
	Route::resource('subcategories', 'SubCategoryController');
	//add routes for requisitions crud
	Route::resource('requisitions', 'RequisitionController');
	Route::get('/api/requisitions/{id}/providers', 'RequisitionController@getProviders');
	Route::get('bussines/{id}', 'RequisitionController@getBussine');
	Route::get('requisitions/subcategory/{id}', 'RequisitionController@getCategory');
	//add routes for status change
	Route::get('requisitions/{id}/validate', 'RequisitionController@validacion');
	Route::get('requisitions/{id}/preauthorize', 'RequisitionController@preauthorize');
	Route::get('requisitions/{id}/authorizar', 'RequisitionController@authorization');
	Route::get('requisitions/{id}/process', 'RequisitionController@process');
	Route::get('requisitions/{id}/payment', 'RequisitionController@payment');
	Route::get('requisitions/{id}/rejected', 'RequisitionController@rejected');
	Route::get('requisitions/{id}/finalizadas', 'RequisitionController@finalizadas');
	Route::post('requisitions/uploadticket', [
		'uses' => 'RequisitionController@uploadticket',
		'as' 	=> 'requisitions.uploadticket'
		]);
	Route::post('requisitions/uploadvoucher', [
		'uses' => 'RequisitionController@uploadvoucher',
		'as' 	=> 'requisitions.uploadvoucher'
		]);
	//routes for comments
	Route::get('/api/requisitions/{requisition}/comments', 'CommentController@index');
	Route::post('/api/requisitions/{requisition}/comment', 'CommentController@store');
	//add routes for select bssines
	Route::get('select/bussine/{id}', 'RequisitionController@selectBussine');
	//add routes for export excel report
	Route::get('/reports-general', 'ExcelController@index');
	Route::post('/search-reports', [
		'uses' => 'ExcelController@search',
		'as' => 'searchreport.store'
		]);
	//reports requisition print
	Route::get('/export-requisition/{id}/print', 'ExcelController@exportRequisition');
	//activities
	Route::get('/activities', 'ActivityController@viewActivity');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [

        'name', 'email', 'password','lastname','address','phone','role','role_id','bussine_id','area_id'
    ];
    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role()
    {
        return $this->belongsTo(Role::class);
    }

    public function bussine()
    {
        return $this->belongsTo(Bussine::class);
    }

    public function area()
    {
        return $this->belongsTo(Area::class);
    }

    public function requisition()
    {
        return $this->hasMany(Requisition::class);
    }

    public function comment()
    {
        return $this->hasMany(Comment::class);
    }

    public function getFullNameAttribute()
    {
        return $this->name . " " . $this->lastname;
    }
    public function getBussineNameAttribute()
    {
        if ($this->bussine_id) {
            return $this->bussine->name;
        }
    }
    public function getAreaNameAttribute()
    {
        if ($this->area_id) {
            return $this->area->name;
        }
    }

    public function getTipoUserAttribute()
    {
        switch ($this->role_id) {
            case '1':
                return 'Administrador';
                break;
            case '2':
                return 'Validación';
                break;
            case '3':
                return 'Preautorizar';
                break;
            case '4':
                return 'Dirección';
                break;
            case '5':
                return 'Compra';
            default:
                return 'Gerente';
        }
    }
    public function getIsAdminAttribute()
    {
        return $this->role_id == 1;
    }
    public function getIsValidationAttribute()
    {
        return $this->role_id == 2;
    }
    public function getIsProcessAttribute()
    {
        return $this->role_id == 2;
    }
    public function getIsPreathorizeAttribute()
    {
        return $this->role_id == 3;
    }
    public function getIsAuthorizeAttribute()
    {
        return $this->role_id == 4;
    }
    public function getIsPaymentAttribute()
    {
        return $this->role_id == 5;
    }
    public function getIsGerenteAttribute()
    {
        return $this->role_id == 6;
    }

    public function activity()
    {
        return $this->hasMany('App\Activity')
            ->with(['user', 'subject'])
            ->latest();
    }
    /**
     * Record new activity for the user.
     *
     * @param  string $name
     * @param  mixed  $related
     * @throws \Exception
     * @return void
     */
    public function recordActivity($name, $related)
    {
        if (! method_exists($related, 'recordActivity')) {
            throw new \Exception('..');
        }
        return $related->recordActivity($name);
    }

    
}

resources/views/layouts/partials/errors.blade.php
@if(count($errors) > 0)
	<div class="alert alert-dismissible alert-danger">
	  <button type="button" class="close" data-dismiss="alert">×</button>
	  <strong>Ups!</strong>
	  @foreach($errors->all() as $error)
	  <li><a href="javascript:void(0)" class="alert-link">{{ $error}}</a></li>
	  @endforeach
	</div>

@endif

resources/views/layouts/partials/menu.blade.php
<div class="panel panel-info">
    <div class="panel-heading text-center">
        <img class="logo_menu" src="{{ asset('images/logo_siscor-bl.png')}}" alt="">
                <i class="material-icons visible-xs-inline-block pull-right btn_close">&#xE5C9;</i>
    </div>

    <div class="panel-body">
        <div class="row sec_welcome">
            <div class="col-sm-3 text-center">
                <img class="circle_avatar" src="{{ Auth::user()->avatar}}" alt="avatar">
            </div>
            <div class="col-sm-9">
                <h5>Bienvenido</h5>
                <h4>{{ Auth::user()->name }}</h4>
            </div>
           
        </div>
        <ul class="nav nav-pills nav-stacked menu_ul">
            <li><a class="collection-item cambio" data-seccion="home" href="/home" ><i class="material-icons">&#xE871;</i> Panel de control</a></li>
            <li><a class="collection-item cambio" data-seccion="requisitions" href="/requisitions/create" ><i class="material-icons">&#xE89C;</i> Nueva Requisición</a></li>
            @if(auth()->user()->role_id == 2)
            <li><a class="collection-item cambio" data-seccion="provider" href="{{ route('provider.index') }}" ><i class="material-icons">&#xE563;</i> Proveedores</a>
            </li>
            @endif
            @if(auth()->user()->is_preathorize || auth()->user()->is_admin)
            <li><a href="/reports-general" class="collection-item"><i class="material-icons">&#xE873;</i>Generar Reportes</a></li>
            @endif
	    @if(auth()->user()->role_id == 4)
            	<li><a href="/reports-general" class="collection-item"><i class="material-icons">&#xE873;</i>Generar Reportes</a></li>
            @endif

            @if(auth()->user()->is_admin)
            <li><a class="collection-item cambio" data-seccion="company" href="{{ route('company.index') }}" ><i class="material-icons">&#xE0AF;</i> Empresas</a>
            </li>
            <li><a class="collection-item cambio" data-seccion="bussine" href="{{ route('bussine.index') }}" ><i class="material-icons">&#xE428;</i> Líneas de negocio</a>
            </li>
            <li><a class="collection-item cambio" data-seccion="area" href="{{ route('area.index') }}"><i class="material-icons">&#xE153;</i> Áreas</a>
            </li>
            <li><a class="collection-item cambio" data-seccion="provider" href="{{ route('provider.index') }}" ><i class="material-icons">&#xE563;</i> Proveedores</a>
            </li>
            <li><a class="collection-item cambio" data-seccion="categories" href="/categories" ><i class="material-icons">&#xE8E6;</i> Categorías</a>
            </li>
            <li><a class="collection-item cambio" data-seccion="subcategories" href="/subcategories" ><i class="material-icons">&#xE8E7;</i> Sub-Categorías</a>
            </li>
            <li><a class="collection-item cambio" data-seccion="users" href="/users" ><i class="material-icons">&#xE7FE;</i> Usuarios</a>
            </li>
            @endif
        </ul>
    </div>
</div>

resources/views/layouts/partials/nav.blade.php
<nav class="navbar">
    <div class="">
        <i class="btn_menu material-icons visible-xs-inline-block">&#xE5D2;</i>

        <!-- Right Side Of Navbar -->
        <ul class="nav navbar-nav ">
            <!-- Authentication Links -->
            @if (Auth::guest())
                <li><a href="{{ route('login') }}">Login</a></li>
            @else
                <unread></unread>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                         <img class="circle_avatar" src="{{ Auth::user()->avatar}}" alt="icon">
                        {{ Auth::user()->full_name }} <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="/profile">Perfil</a></li>
                        <li>
                            <a href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                                Logout
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </li>
                    </ul>
                </li>
            @endif
        </ul>
    </div>
</nav>

resources/views/layouts/partials/success.blade.php
@if(session('notification'))
    <div class="alert alert-success">
      {{ session('notification')}}
    </div>
@endif